# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true


run:
  name: "nl-summer19-windsolar" # use this to keep track of runs with different settings
  #cutout: europe-2023-era5
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: false

scenario:
  clusters: [1]
  opts: ['']

countries: ['NL']

snapshots:
  start: "2023-07-01"
  end: "2023-07-08"

electricity:
  co2limit_enable: false
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [offwind-dc, OCGT, solar]
    StorageUnit: []
    Store: []
    Link: []

  renewable_carriers: [offwind-dc, solar]
  estimate_renewable_capacities:
    enable: true
    from_gem: false
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-dc
      PV: solar

atlite:
  default_cutout: europe-2023-sarah3-era5
  cutouts:
    europe-2023-sarah3-era5:
      module: [sarah, era5]
      x: [3.0, 4.5]
      y: [50.5, 52.0]
      time: ["2023-07-01", "2023-07-08"]

renewable:
  offwind-ac:
    max_depth: false
  offwind-dc:
    max_depth: false
  offwind-float:
    max_depth: false
    min_depth: false


clustering:
  exclude_carriers: ["OCGT", "coal"]
  temporal:
    resolution_elec: 24h

lines:
  dynamic_line_rating:
    activate: false
    max_line_rating: 1.3


solving:
  solver:
    name: highs
    options: highs-simplex

  check_objective:
    enable: false
    expected_value: 3.8120188094e+07
